%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: F:\IITM\github\WIPO\Data\wipo_pub_1055_2021-conventional.xlsx
%    Worksheet: Overall Metadata
%
% Auto-generated by MATLAB on 30-Dec-2021 10:21:10
clc
clear all
close all
% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 29);

% Specify sheet and range
opts.Sheet = "Overall Metadata";
opts.DataRange = "A2:AC117210";

% Specify column names and types
opts.VariableNames = ["SNo", "DWPIAccessionNumber", "PublicationNumberWithHyperlinksToPatentDocuments", "EarliestPriorityYearYearOfFirstFiling", "EarliestPublicationYear", "DWPIFamilyMembersExportDateJul202020", "UtilityModelPatent", "UtilityModelPatenthowItWasTreatedInTheAnalysis", "PatentFamiliesWithAtLeastOnePCTWOFamilyMember", "PatentFamiliesWithAtLeastOneEPEPOFamilyMember", "ApplicantsSectors", "ApplicantNamesStandardized", "DWPIApplicantExportedOnJul202020", "AssigneeOriginalCountryRegion", "AssigneeOriginalWaddress", "ProtectionLocationsCountryFullNameThisIsOfficeOfFirstFilingsAnd", "GeographicalRegions", "PatentFamilySizeUniquePatentOfficesincludingWIPO", "InventorCountry", "ConventionalCategory", "SubCategoriesHearing14198", "SubCategoriesCognition1416", "SubCategoriesMobilty63245", "SubCategoriesSelfcare6410", "SubCategoriesEnvironment21326", "SubCategoriesVision8133", "SubCategoriesCommunication6899", "Link", "PublicationNumber"];
opts.VariableTypes = ["double", "double", "string", "double", "double", "string", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "string", "string", "string", "categorical", "categorical", "double", "categorical", "categorical", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["PublicationNumberWithHyperlinksToPatentDocuments", "DWPIFamilyMembersExportDateJul202020", "DWPIApplicantExportedOnJul202020", "AssigneeOriginalCountryRegion", "AssigneeOriginalWaddress", "SubCategoriesHearing14198", "SubCategoriesCognition1416", "SubCategoriesMobilty63245", "SubCategoriesSelfcare6410", "SubCategoriesEnvironment21326", "SubCategoriesVision8133", "SubCategoriesCommunication6899", "Link", "PublicationNumber"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["PublicationNumberWithHyperlinksToPatentDocuments", "DWPIFamilyMembersExportDateJul202020", "UtilityModelPatent", "UtilityModelPatenthowItWasTreatedInTheAnalysis", "PatentFamiliesWithAtLeastOnePCTWOFamilyMember", "PatentFamiliesWithAtLeastOneEPEPOFamilyMember", "ApplicantsSectors", "ApplicantNamesStandardized", "DWPIApplicantExportedOnJul202020", "AssigneeOriginalCountryRegion", "AssigneeOriginalWaddress", "ProtectionLocationsCountryFullNameThisIsOfficeOfFirstFilingsAnd", "GeographicalRegions", "InventorCountry", "ConventionalCategory", "SubCategoriesHearing14198", "SubCategoriesCognition1416", "SubCategoriesMobilty63245", "SubCategoriesSelfcare6410", "SubCategoriesEnvironment21326", "SubCategoriesVision8133", "SubCategoriesCommunication6899", "Link", "PublicationNumber"], "EmptyFieldRule", "auto");

% Import the data
conventionalTable = readtable("F:\IITM\github\WIPO\Data\wipo_pub_1055_2021-conventional.xlsx", opts, "UseExcel", false);


% Clear temporary variables
clear opts

% Table separation
%removevars
conventional_wheelchair = removevars(conventionalTable,{'SNo','DWPIAccessionNumber','DWPIFamilyMembersExportDateJul202020','EarliestPublicationYear','UtilityModelPatent','AssigneeOriginalCountryRegion', 'AssigneeOriginalWaddress', 'InventorCountry', 'ConventionalCategory', 'SubCategoriesHearing14198', ...
    'SubCategoriesCognition1416','SubCategoriesSelfcare6410', 'SubCategoriesEnvironment21326', 'SubCategoriesVision8133', 'SubCategoriesCommunication6899','DWPIApplicantExportedOnJul202020','PatentFamilySizeUniquePatentOfficesincludingWIPO',});

S = conventional_wheelchair.PublicationNumber(10);
A = webread(strcat("https://patents.google.com/patent/",S,"/en?oq=",S),'weboption','text/plain');

